[package]
name = "painter"
version = "1.0.0"
authors = ["Kied T L"]
edition = "2018"

[target.'cfg(windows)'.dependencies]

[dependencies]
winapi = { version = "0.3", features = ["winuser"] }
clap = {version = "2.32", features = ["yaml"]}